src/Entity/Articles.php
<?php

namespace App\Entity;

use App\Repository\ArticlesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ArticlesRepository::class)
 */
class Articles
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $Titre;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $Auteur;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Description;

    /**
     * @ORM\Column(type="date")
     */
    private $DateAjout;

    /**
     * @ORM\OneToMany(targetEntity=Stock::class, mappedBy="produit")
     */
    private $stocks;

    public function __construct()
    {
        $this->stocks = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(string $id): self
    {
        $this->id = $id;

        return $this;
    }

    public function getTitre(): ?string
    {
        return $this->Titre;
    }

    public function setTitre(string $Titre): self
    {
        $this->Titre = $Titre;

        return $this;
    }

    public function getAuteur(): ?string
    {
        return $this->Auteur;
    }

    public function setAuteur(string $Auteur): self
    {
        $this->Auteur = $Auteur;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getDateAjout(): ?\DateTimeInterface
    {
        return $this->DateAjout;
    }

    public function setDateAjout(\DateTimeInterface $DateAjout): self
    {
        $this->DateAjout = $DateAjout;

        return $this;
    }

    /**
     * @return Collection|Stock[]
     */
    public function getStocks(): Collection
    {
        return $this->stocks;
    }

    public function addStock(Stock $stock): self
    {
        if (!$this->stocks->contains($stock)) {
            $this->stocks[] = $stock;
            $stock->setProduit($this);
        }

        return $this;
    }

    public function removeStock(Stock $stock): self
    {
        if ($this->stocks->contains($stock)) {
            $this->stocks->removeElement($stock);
            // set the owning side to null (unless already changed)
            if ($stock->getProduit() === $this) {
                $stock->setProduit(null);
            }
        }

        return $this;
    }
}

src/Controller/AdminProduitsController.php
<?php

namespace App\Controller;

use App\Entity\Articles;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;

class AdminProduitsController extends AbstractController
{
    /***@Route("/admin/produits/list", name="admin_produits.list")*/
    public function index()
    {
        $produitsRepository= $this->getDoctrine()->getRepository(Articles::class);
        $produits= $produitsRepository->findAll();
        return $this->render('admin_produits/index.html.twig',['produits' => $produits]);
    }

    /*** @Route("/admin/{id}", name="admin.produit.edit")*/
    public function edit()
    {
        return $this->render('admin_produits/edit.html.twig');
    }

    /*** @Route  ("/admin/produit/add", name="admin.produit.add")*/
    public function delete(Request $request)
    {
        return $this->render('admin_produits/add.html.twig');
    }

    /*** @Route("/admin/produit/delete/{id}", name="admin.produit.delete", methods="DELETE")*/
    public function add(Articles$produit,Request$request)
    {
        return $this->redirectToRoute('admin.produit.list');
    }
}

templates/admin_produits/details.html.twig
{% extends'base.html.twig' %}{% block body %}<div class="container"><div class="jumbotron"><div class="container"><div class="row"><div class="col-md-8"></div><div class="col-md-4"><h1>{{ produit.titre}}</h1><h2>{{ produit.stockQte}} pièces -{{ produit.poids}} Kg</h2><div class="text-primary" style="font-size: 4rem;font-weight: bold;">{{ produit.PriceTTC| number_format(0,'',' ') }} €</div><a href="#" class="btnbtn-primary">Contactez nous</a></div></div></div></div><div class="container mt-4"><p>{{ produit.description| nl2br }}</p><div class="row"><div class="col-md-8"><h2>Caractéristiques</h2><table class="table table-striped"><tr><td>Stock</td><td>{{ produit.stockQte}}</td></tr><tr><td>Poids</td><td>{{ produit.poids}} Kg</td></tr><tr><td>Couleur</td><td>{{ produit.couleurType}}</td></tr></table></div><div class="col-md-4"><h2>Spécificités</h2></div></div></div></div>{% endblock%}

templates/admin_produits/index.html.twig
{% extends 'base.html.twig' %}
{% block title 'Gérerles produits' %}
{% block body %}
    <div class="container mt-4">
    <h1>Gérerles Produits</h1>
    <a href="{{ path('admin.produit.add') }}" class="btnbtn-success ">Ajouter</a>
    <table class="table table-striped">
        <thead>
        <tr>
            <th>Titre</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>{% for produitin produits%}
            <tr>
            <td>{{ produit.titre}}</td>
            <td>
                <a href="{{ path('admin.produit.edit', {id: produit.id}) }}" class="btnbtn-secondary">Editer</a>
            </td>
            </tr>
        {% endfor%}
        </tbody>
    </table>
    </div>
{% endblock%}